"""
helmet_train.py — Train YOLOv8 for helmet/no-helmet detection.

Dataset: Safety Helmet Detection (Roboflow Universe)
  https://universe.roboflow.com/joseph-nelson/hard-hat-workers

Steps:
  1. pip install roboflow
  2. Set your Roboflow API key below (or export ROBOFLOW_API_KEY=...)
  3. Run: python models/helmet_train.py
  4. Trained weights will be at: runs/detect/helmet-detector/weights/best.pt

Classes produced:
  0 = helmet       (rider wearing helmet)
  1 = no_helmet    (rider NOT wearing helmet — triggers challan)
"""

import os
import torch
from ultralytics import YOLO

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
ROBOFLOW_API_KEY = os.environ.get("ROBOFLOW_API_KEY", "YOUR_API_KEY_HERE")
DATASET_DIR      = "helmet_dataset"   # where the downloaded dataset will live
BASE_MODEL       = "yolov8n.pt"       # start from nano — fast, good enough
EPOCHS           = 50
IMG_SIZE         = 640
BATCH            = 16
PROJECT          = "runs/detect"
RUN_NAME         = "helmet-detector"

# ---------------------------------------------------------------------------
# Step 1: Download dataset from Roboflow
# ---------------------------------------------------------------------------

def download_dataset():
    try:
        from roboflow import Roboflow
    except ImportError:
        raise SystemExit(
            "roboflow package not installed. Run:\n"
            "  pip install roboflow"
        )

    if ROBOFLOW_API_KEY == "YOUR_API_KEY_HERE":
        raise SystemExit(
            "Set your Roboflow API key:\n"
            "  export ROBOFLOW_API_KEY=<your_key>\n"
            "or edit ROBOFLOW_API_KEY in this file.\n\n"
            "Get a free key at https://roboflow.com"
        )

    rf = Roboflow(api_key=ROBOFLOW_API_KEY)

    # Safety Helmet Detection dataset — 5k images, helmet / no-helmet / person
    project = rf.workspace("joseph-nelson").project("hard-hat-workers")
    dataset = project.version(1).download("yolov8", location=DATASET_DIR)
    return dataset.location


def find_data_yaml():
    """Find the data.yaml generated by Roboflow inside DATASET_DIR."""
    for root, _, files in os.walk(DATASET_DIR):
        for f in files:
            if f == "data.yaml":
                return os.path.join(root, f)
    raise FileNotFoundError(f"data.yaml not found under {DATASET_DIR}/")


# ---------------------------------------------------------------------------
# Step 2: Train
# ---------------------------------------------------------------------------

def train(data_yaml: str):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Training on: {device}")
    print(f"Dataset:     {data_yaml}")
    print(f"Base model:  {BASE_MODEL}")

    model = YOLO(BASE_MODEL)
    model.train(
        data=data_yaml,
        epochs=EPOCHS,
        imgsz=IMG_SIZE,
        batch=BATCH,
        device=device,
        project=PROJECT,
        name=RUN_NAME,
        exist_ok=True,
        patience=15,        # early stopping
        save=True,
        plots=True,
        verbose=True,
    )

    weights = os.path.join(PROJECT, RUN_NAME, "weights", "best.pt")
    print(f"\nTraining complete. Best weights: {weights}")
    return weights


# ---------------------------------------------------------------------------
# Step 3: Quick validation
# ---------------------------------------------------------------------------

def validate(weights: str, data_yaml: str):
    model = YOLO(weights)
    metrics = model.val(data=data_yaml)
    print("\n=== Validation Metrics ===")
    print(f"mAP50:    {metrics.box.map50:.3f}")
    print(f"mAP50-95: {metrics.box.map:.3f}")
    print(f"Precision:{metrics.box.p[0]:.3f}")
    print(f"Recall:   {metrics.box.r[0]:.3f}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--skip-download",
        action="store_true",
        help="Skip Roboflow download if dataset already present",
    )
    parser.add_argument(
        "--data-yaml",
        default=None,
        help="Path to data.yaml (overrides auto-detection)",
    )
    args = parser.parse_args()

    if args.data_yaml:
        data_yaml = args.data_yaml
    elif args.skip_download:
        data_yaml = find_data_yaml()
    else:
        print("Downloading dataset from Roboflow...")
        download_dataset()
        data_yaml = find_data_yaml()

    print(f"Using data.yaml: {data_yaml}")
    weights = train(data_yaml)
    validate(weights, data_yaml)
